// Mocks generated by Mockito 5.1.0 from annotations
// in seventh_player/test/features/video_player/data/repositories/video_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:seventh_player/features/video_player/data/datasource/video_player_datasource.dart'
    as _i2;
import 'package:seventh_player/features/video_player/data/model/video_player_model.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [VideoPlayerDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoPlayerDatasource extends _i1.Mock
    implements _i2.VideoPlayerDatasource {
  MockVideoPlayerDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.VideoPlayerModel?> getUrl(String? fileName) =>
      (super.noSuchMethod(Invocation.method(#getUrl, [fileName]),
              returnValue: Future<_i4.VideoPlayerModel?>.value())
          as _i3.Future<_i4.VideoPlayerModel?>);
}
