// Mocks generated by Mockito 5.1.0 from annotations
// in seventh_player/test/features/login/data/repositories/login_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:dartz/dartz.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:seventh_player/cores/errors.dart' as _i5;
import 'package:seventh_player/features/login/data/datasources/login_datasource.dart'
    as _i2;
import 'package:seventh_player/features/login/data/models/login_model.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [LoginDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginDatasource extends _i1.Mock implements _i2.LoginDatasource {
  MockLoginDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ErrorOnApi, _i6.LoginModel>?> getToken(
          String? username, String? password) =>
      (super.noSuchMethod(Invocation.method(#getToken, [username, password]),
              returnValue:
                  Future<_i4.Either<_i5.ErrorOnApi, _i6.LoginModel>?>.value())
          as _i3.Future<_i4.Either<_i5.ErrorOnApi, _i6.LoginModel>?>);
}
